### ISSUE TITLE
Adding ellipsis option for treemap chart

### ISSUE THREAD

**Issue by amirs-kov** [nhn/tui.chart#274]
## Version
3.10.1 - latest

## Development Environment
Chrome, Mac OSX, GCP environment

## Current Behavior
currently there is no option to trim the label to fit the size of the rect it sits in. 
Since the component renders a svg with text objects that are not inherited, the width of the text is not related to the width of the rect. 
It's also not possible to fix a width to the text objects through css with this style:

```css
.tui-chart svg text {
  width: inherit;
  white-space: nowrap;
  text-overflow: ellipsis;
  width: 10;
}
```

## Expected Behavior
It will make more sense if the max width of the text will be of the rect it sits inside and '...' will be added instead of the text trimmed. The full text can be shown in the tooltip. 
Perhaps, it is also possible to just add it is a configuration to be set by the options.
